
require('paq_init')
require('keybinds')
require('core/main')
require('core/colorscheme')
require('core/nvim-comment')
require('plugins/lsp/config')
require('plugins/lsp/nvim-cmp')
require('plugins/lsp/snippets')
require('plugins/nvim-tree')
require('plugins/go')
require('plugins/lualine')
