
require('keybinds')
require('plugins')
require('core/colorscheme')
require('core/main')
require('core/nvim-comment')
require('plugins/lsp/lsp-zero')
require('plugins/notify')
require('plugins/nvim-lsputils')
require('plugins/nvim-tree')
require('plugins/formatter')
require('plugins/treesitter')
require('plugins/which-key')
